<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
 <ItemGroup Label="ProjectConfigurations"><ProjectConfiguration Include="Debug|x64"><Configuration>Debug</Configuration><Platform>x64</Platform></ProjectConfiguration></ItemGroup>
 <PropertyGroup Label="Globals"><WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion></PropertyGroup>
 <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
 <PropertyGroup Label="Configuration"><ConfigurationType>Application</ConfigurationType><PlatformToolset>v145</PlatformToolset><UseDebugLibraries>true</UseDebugLibraries><CharacterSet>Unicode</CharacterSet></PropertyGroup>
 <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
 <PropertyGroup><OutDir>$(ProjectDir)build\</OutDir><IntDir>$(ProjectDir)build\obj\</IntDir></PropertyGroup>
 <ItemDefinitionGroup><ClCompile><LanguageStandard>stdcpp20</LanguageStandard><AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions><WarningLevel>Level3</WarningLevel><PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions></ClCompile><Link><SubSystem>Console</SubSystem><AdditionalDependencies>User32.lib;Gdi32.lib;D3D11.lib;Windowscodecs.lib;Ole32.lib;%(AdditionalDependencies)</AdditionalDependencies></Link></ItemDefinitionGroup>
 <ItemGroup>
  <ClCompile Include="CombatTests.cpp" />
  <ClCompile Include="../Engine/Core/Profiler.cpp" />
  <ClCompile Include="../Game/Data/GameData.cpp" />
  <ClCompile Include="../Game/Stats/PlayerStat.cpp" />
  <ClCompile Include="../Game/Player.cpp" />
  <ClCompile Include="../Game/Monster.cpp" />
  <ClCompile Include="../Game/World/GameWorld.cpp" />
  <ClCompile Include="../Game/World/Ground.cpp" />
  <ClCompile Include="../Game/World/WorldItem.cpp" />
  <ClCompile Include="../Game/Entity/GameObject.cpp" />
  <ClCompile Include="../Game/Entity/Character.cpp" />
  <ClCompile Include="../Game/Animation/Animator.cpp" />
  <ClCompile Include="../Game/Combat/PlayerAttack.cpp" />
  <ClCompile Include="../Game/Combat/SkillObject.cpp" />
  <ClCompile Include="../Game/Effects/HitEffect.cpp" />
  <ClCompile Include="../Engine/Core/CombatHud.cpp" />
  <ClCompile Include="../Engine/Core/UIManager.cpp" />
  <ClCompile Include="../Engine/Graphics/Renderer.cpp" />
  <ClCompile Include="../Engine/Graphics/ResourceManager.cpp" />
  <ClCompile Include="../Engine/ThirdParty/stb/StbImage.cpp" />
 </ItemGroup>
 <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ItemGroup><ClCompile Include="../Game/World/WorldCombat.cpp" /></ItemGroup>
</Project>
